# https://geshan.com.np/blog/2021/12/docker-postgres/

version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-todo-list
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  todo-list:
    container_name: todo-list
    image: todo-list
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 9010:9010
    environment:
      - DIALECT=postgres
      - HOST=postgres-todo-list
      - DBPORT=5432
      - USER=postgres
      - PASSWORD=wjswldhks
      - NAME=postgres
      - PORT=9010
    build:
      context: ./
      dockerfile: ./Dockerfile
