# https://geshan.com.np/blog/2021/12/docker-postgres/

version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-todo-list
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wjswldhks
    ports:
      - "35432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#   api:
#     container_name: postgres-server
#     build:
#       .
#       # context: ./
#       # target: production
#     image: postgres:latest
#     depends_on:
#       - db
#     ports:
#       - 9010:9010
#     environment:
#       # NODE_ENV: production
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: wjswldhks
#       DB_NAME: todo_list_second
#     links:
#       - db
#     volumes:
#       - "./:/src"
# volumes:
#   db:
#     driver: local
