// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Title       string `json:"Title"`
	Description string `json:"Description"`
	Condition   bool   `json:"Condition"`
}

type Todo struct {
	Title       string `json:"Title"`
	Description string `json:"Description"`
	Condition   bool   `json:"Condition"`
}
